name: Linux CI (MinGW)

on: [push, pull_request]

jobs:
  build-linux:
    name: ${{ matrix.platform.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux (x86_64),  shell: bash, makefile: Makefile }

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        # use apt-spy2 to select closest apt mirror,
        # which helps avoid connectivity issues in Azure;
        # see https://github.com/actions/virtual-environments/issues/675
        sudo gem install apt-spy2
        sudo apt-spy2 check
        sudo apt-spy2 fix --commit
        # after selecting a specific mirror, we need to run 'apt-get update'
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        sudo apt-get install -y libsdl2-dev libmad0-dev libopus-dev libvorbis-dev zlib1g-dev libvorbisfile3 libopusfile-dev zip

    - name: Build Linux
      run: |
        set -eu
        parallel="$(nproc)"
        exec $MAKE_CMD USE_SDL2=1 CC=$CC AS=$AS RANLIB=$RANLIB AR=$AR STRIP=$STRIP -f ${{ matrix.platform.makefile }} -j"${parallel}" -C Quake
        
    - name: Upload linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux64
        path: |
          Quake/quakespasm
