name: Linux CI (MinGW)

on: [push, pull_request]

jobs:
  build-linux:
    name: ${{ matrix.platform.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux (x86_64),  shell: bash, makefile: Makefile }

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        sudo apt-get install -y libsdl2-dev libmad0-dev libopus-dev libvorbis-dev zlib1g-dev libvorbisfile3 libopusfile-dev

    - name: Set environment variables
      run: |
        echo "TARGET=x86_64-linux-gnu" >> $GITHUB_ENV
        echo "PREFIX=/opt/cross_linux64" >> $GITHUB_ENV
        echo "PATH=$PREFIX/bin:$PATH" >> $GITHUB_ENV
        echo "MAKE_CMD=make" >> $GITHUB_ENV
        echo "CC=$TARGET-gcc" >> $GITHUB_ENV
        echo "AS=$TARGET-as" >> $GITHUB_ENV
        echo "RANLIB=$TARGET-ranlib" >> $GITHUB_ENV
        echo "AR=$TARGET-ar" >> $GITHUB_ENV
        echo "STRIP=$TARGET-strip" >> $GITHUB_ENV

    - name: Build Linux
      run: |
        set -eu
        parallel="$(nproc)"
        exec $MAKE_CMD USE_SDL2=1 CC=$CC AS=$AS RANLIB=$RANLIB AR=$AR STRIP=$STRIP -f ${{ matrix.platform.makefile }} -j"${parallel}" -C Quake

    - name: Upload QSSM
      uses: actions/upload-artifact@v3
      with:
        name: QSSM
        path: |
            Quake
