name: macOS

on:
  push

jobs:
  build:
    name: arm64/intel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: macOS
      if: runner.os == 'macOS'
      run: |
          cd MacOSX
          ./build-macos.sh

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      if: runner.os == 'macOS'
      with:
        name: macos
        path: |
          MacOSX/build/Release/*.zip
