name: Windows CI (MinGW)

on: [push, pull_request]

jobs:
  build-mingw:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows (mingw32),  os: windows-latest, shell: 'msys2 {0}', msystem: mingw32, msys-env: mingw-w64-i686, makefile: Makefile.w32 }
        - { name: Windows (mingw64),  os: windows-latest, shell: 'msys2 {0}', msystem: mingw64, msys-env: mingw-w64-x86_64, makefile: Makefile.w64 }

    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.platform.msystem }}
        install: base-devel
          ${{ matrix.platform.msys-env }}-gcc
          ${{ matrix.platform.msys-env }}-glslang

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set environment variables
      run: |
        echo "TARGET=x86_64-w64-mingw32" >> $GITHUB_ENV
        echo "PREFIX=/opt/cross_win64" >> $GITHUB_ENV
        echo "PATH=$PREFIX/bin:$PATH" >> $GITHUB_ENV
        echo "MAKE_CMD=make" >> $GITHUB_ENV
        echo "CC=$TARGET-gcc" >> $GITHUB_ENV
        echo "AS=$TARGET-as" >> $GITHUB_ENV
        echo "RANLIB=$TARGET-ranlib" >> $GITHUB_ENV
        echo "AR=$TARGET-ar" >> $GITHUB_ENV
        echo "WINDRES=$TARGET-windres" >> $GITHUB_ENV
        echo "STRIP=$TARGET-strip" >> $GITHUB_ENV
        export QSS_CFLAGS="-DQSS_REVISION=`git rev-parse HEAD`"
        export QSS_LDFLAGS="-Wl,--allow-multiple-definition"

    - name: Build MinGW
      run: |
        set -eu
        parallel="$(getconf _NPROCESSORS_ONLN)"
        exec $MAKE_CMD USE_SDL2=1 CC=$CC AS=$AS RANLIB=$RANLIB AR=$AR WINDRES=$WINDRES STRIP=$STRIP -f ${{ matrix.platform.makefile }} -j"${parallel}" -C Quake

    - name: Upload QSSM
      uses: actions/upload-artifact@v3
      with:
        name: QSSM archive (${{ matrix.platform.msystem }})
        path: |
            Quake/*.exe
            Quake/*.dll
