name: Windows CI (MinGW SYS2)

on: [push, pull_request]

jobs:
  build:
    name: w64
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        release: false
        install: >
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-opus
          mingw-w64-x86_64-opusfile
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-libmad
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-libzip
          cmake
          zip
          cp "C:/mingw64/include/zlib.h" "${{ github.workspace }}/Windows/codecs/include/zlib.h"
      
    - name: Build QSS-M
      run: bash build-w64.sh
